# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Harbor and Spruce
logo_title: H + S
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/harborandspruce" # the subpath of your site, e.g. /blog
url: "http://harborandspruce.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: harborandspruce
github_username:  jekyll
lightbox-js-path: /assets/js/lightbox.js
lightbox-css-path: /assets/css/lightbox.css
fa-js-path: /assets/js/all.js


# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found


#Staticman config
staticman_url: https://harborspruce-staticman2.herokuapp.com/v2/entry/sjdodge123/harborandspruce/master/comments
reCaptcha:
    siteKey: 6LcvkL0aAAAAABxdrYGGCzOwtBPTeFZn8It5549y
    secret: I0ot3veuOFP0FsEZBFcbJmlZQdlJbltiMvEXUTceLEVz29NwYO66xtqFSW9xUo2hzccihyeU7gCd14KMo3mMPchM6mqx4xQmQQ1QduqsVINp5FEaKhRx8FW9T3u0j51vZdpRfG/5ufU4Vz3Y0lsRtSYmaPvkPrslurrr4pIOtCHU1mOXt1XcsreE+HPJvfmUFO4SaaL8Vn9iNFj92/hTwCEsCXo8768FDX+ib8eokS9LCDiJ2PrwiNn1XES19Mhi9iz9pwMQRcrAYC6LOV2AJnlErcP5IXBC8LrLUxYGul8Y6z/NtwwKFASOB9eyKv6XVBmp2WoFHTWbHHiAbyVRmCVrCEKjV6x41PUYpYkxZLUn3CPfI3eXzkEy7cqUH2X0Le+8mcqpGnMVL0CZnialYeNYMpyMftxxZ59zQN6mSg5mO/UdbS79U4/87y7thXMvsffSqz+05cy/4p3qrkmBZodQZlhqxLqEF3fEBpo3hIS2wHiOmqSB6ynvuyTE72z4dMhtS+yQFHgGOAQ0VBsaGIykQapXxb4blalExxW/n+23M9riefaXU8jNYsfVhgshPW711B1byVrxuQphSuy9yWHlf+Mu4zYKK04qlARWut/BOF/NR53LYJGZMkG1otb8oNBGnUMl8LP/Z9bfFSROoHBReKMwfIBgkWw0o2S5tXU=

#Pagination Settings
paginate: 6

#Social
minima:
  social_links:
    instagram: harborandspruce

# Build settings

show_excerpts: true
theme: minima
environment: production
disqus:
    shortname: my_disqus_shortname
plugins:
  - jekyll-feed
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
